global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sesame-app'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: local
          region: us-east-1
  - job_name: 'php'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
